language: ruby

rvm:
  # - 2.2
  - 2.3
  # - 2.4
  # - rbx-2
  # - rbx
  # - jruby-1.7
  # - jruby

gemfile:
  - spec/gemfiles/Gemfile.edge
  # - spec/gemfiles/Gemfile.rails-3.2.x
  # - spec/gemfiles/Gemfile.rails-4.0.x
  # - spec/gemfiles/Gemfile.rails-4.1.x
  # - spec/gemfiles/Gemfile.rails-4.2.x
  # - spec/gemfiles/Gemfile.sequel-3.x

env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/que-test
  - DATABASE_URL=postgres://postgres:@localhost:5433/que-test
  # - DATABASE_URL=postgres://postgres:@localhost:5434/que-test
  # - DATABASE_URL=postgres://postgres:@localhost:5435/que-test

before_install:
  - sudo apt-get update
  - sudo apt-get remove postgresql-9.1
  - sudo apt-get remove postgresql-9.2
  - sudo apt-get install postgresql-9.3
  - sudo apt-get install postgresql-9.4
  - sudo apt-get install postgresql-9.5
  - sudo apt-get install postgresql-9.6
  - sudo sed -i "s/port = ..../port = 5432/g" /etc/postgresql/9.3/main/postgresql.conf
  - sudo sed -i "s/port = ..../port = 5433/g" /etc/postgresql/9.4/main/postgresql.conf
  - sudo sed -i "s/port = ..../port = 5434/g" /etc/postgresql/9.5/main/postgresql.conf
  - sudo sed -i "s/port = ..../port = 5435/g" /etc/postgresql/9.6/main/postgresql.conf
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start

before_script:
  - psql -c 'create database "que-test"' -U postgres
  - bundle exec ruby -r sequel -r ./lib/que -e 'Que.connection=Sequel.connect("postgres://localhost/que-test"); Que.migrate!'

script: "bundle exec rake"

notifications:
  email: false
