language: ruby
rvm:
  - "2.1"
  - "2.2"
  - "2.3"
  - "rbx-2"
before_script:
  - psql -c 'create database "que-test"' -U postgres
  - bundle exec ruby -r sequel -r ./lib/que -e 'Que.connection_proc=Sequel.connect("postgres://localhost/que-test").method(:synchronize); Que.migrate!'

script: "./spec/travis.rb"

addons:
  postgresql: 9.4
