language: ruby
# cache: bundler

rvm:
  # - 2.2
  - 2.3
  # - 2.4
  # - rbx-2
  # - rbx
  # - jruby-1.7
  # - jruby

gemfile:
  - spec/gemfiles/Gemfile.edge
  - spec/gemfiles/Gemfile.rails-4.2.x
  # - spec/gemfiles/Gemfile.rails-4.1.x
  # - spec/gemfiles/Gemfile.rails-4.0.x
  # - spec/gemfiles/Gemfile.sequel-3.x

env:
  - PG_VERSION=9.3
  - PG_VERSION=9.4
  - PG_VERSION=9.5
  # - PG_VERSION=9.6

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install postgresql-$PG_VERSION
  - sudo sed -i "s/port = ..../port = 5432/g" /etc/postgresql/$PG_VERSION/main/postgresql.conf
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $PG_VERSION

before_script:
  - psql -c 'create database "que-test"' -U postgres
  - bundle exec ruby -r sequel -r ./lib/que -e 'Que.connection=Sequel.connect("postgres://localhost/que-test"); Que.migrate!'

script: "bundle exec rake"

notifications:
  email: false
