default_environment: &default_environment
  GEMFILE_VERSIONS: "current old older oldest"
  PG_VERSIONS: "9.4 9.5 9.6"
  PG_PORTS: "5432 5433 5434"

defaults: &defaults
  working_directory: ~/que
  docker:
    - image: chanks/que-circleci:0.0.2
  steps:
    - checkout

    # Use all our Gemfiles as a Bundler cache key.
    - run: md5sum spec/gemfiles/Gemfile.* > bundler_checksum

    # The CircleCI docs say we can use {{.Environment.RUBY_VERSION}} in the
    # cache key, which would be cleaner, but all I get is `<no value>` :/ So, be
    # a bit hackier.
    - run: echo $RUBY_VERSION >> bundler_checksum

    - restore_cache:
        key: bundler-cache-{{checksum "bundler_checksum"}}

    - run:
        command: |
          for GEMFILE_VERSION in $GEMFILE_VERSIONS
          do
            rvm $RUBY_VERSION do \
              bundle install \
                --gemfile spec/gemfiles/Gemfile.$GEMFILE_VERSION \
                --path vendor
          done

    - save_cache:
        key: bundler-cache-{{checksum "bundler_checksum"}}
        paths:
          # Cache Gemfile.locks and gems vendored under this directory.
          - spec/gemfiles

    - run:
        command: |
          for PG_VERSION in $PG_VERSIONS
          do
            echo "host all all 127.0.0.1/32 trust" > \
              /etc/postgresql/$PG_VERSION/main/pg_hba.conf
            echo "local all all trust" >> \
              /etc/postgresql/$PG_VERSION/main/pg_hba.conf
          done

    # Fix Postgres SSL certificate error.
    # From: https://github.com/nimiq/docker-postgresql93/issues/2
    - run:
        command: |
          mkdir /etc/ssl/private-copy
          mv /etc/ssl/private/* /etc/ssl/private-copy/
          rm -r /etc/ssl/private
          mv /etc/ssl/private-copy /etc/ssl/private
          chmod -R 0700 /etc/ssl/private
          chown -R postgres /etc/ssl/private

    - run: service postgresql start
    - run:
        command: |
          for PG_PORT in $PG_PORTS
          do
            createdb que-test -U postgres -p $PG_PORT
          done

    - run:
        command: |
          for PG_PORT in $PG_PORTS
          do
            (
              for GEMFILE_VERSION in $GEMFILE_VERSIONS
              do
                DATABASE_URL="postgres://postgres:@localhost:$PG_PORT/que-test" \
                BUNDLE_GEMFILE="spec/gemfiles/Gemfile.$GEMFILE_VERSION" \
                rvm $RUBY_VERSION do bundle exec rake
              done
            ) &
          done
          wait

version: 2
jobs:
  ruby_2_2:
    <<: *defaults
    environment:
      <<: *default_environment
      RUBY_VERSION: 2.2

  ruby_2_3:
    <<: *defaults
    environment:
      <<: *default_environment
      RUBY_VERSION: 2.3

  ruby_2_4:
    <<: *defaults
    environment:
      <<: *default_environment
      RUBY_VERSION: 2.4

workflows:
  version: 2
  build_all_rubies:
    jobs:
      - ruby_2_2
      - ruby_2_3
      - ruby_2_4
