version: 2
jobs:
  build:
    working_directory: ~/que
    docker:
      - image: circleci/ruby:2.4
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: que-test
      - image: circleci/postgres:9.5
        command: -p 5433:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: que-test
      - image: circleci/postgres:9.4
        command: -p 5434:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: que-test
    steps:
      - checkout
      - run: bundle
      - run: DATABASE_URL=postgres://postgres:postgres@localhost:5432/que-test TEST_OPTS="--verbose --profile" bundle exec rake
      - run: DATABASE_URL=postgres://postgres:postgres@localhost:5433/que-test TEST_OPTS="--verbose --profile" bundle exec rake
      - run: DATABASE_URL=postgres://postgres:postgres@localhost:5434/que-test TEST_OPTS="--verbose --profile" bundle exec rake
