version: 2
jobs:
  build:
    working_directory: ~/que
    docker:
      - image: circleci/ruby:2.4
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/que-test
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: que-test
    steps:
      - checkout
      - run: TEST_OPTS="--verbose --profile" bundle exec rake
