defaults: &defaults
  working_directory: ~/que
  docker:
    - image: chanks/que-circleci:0.0.2
  environment:
    - GEMFILE_VERSIONS: "current old older oldest"
    - PG_VERSIONS: "9.4 9.5 9.6"
    - PG_PORTS: "5432 5433 5434"
  steps:
    - checkout

    # Concatenate all our Gemfiles together, so we can update our Bundler
    # cache key whenever any of them change.
    - run: md5sum spec/gemfiles/Gemfile.* > bundler_checksum

    - restore_cache:
        key: bundler-cache-{{.Environment.RUBY_VERSION}}-{{checksum "bundler_checksum"}}

    - run:
        command: |
          for gemfile_version in $GEMFILE_VERSIONS
          do
            rvm $RUBY_VERSION do bundle install --gemfile spec/gemfiles/Gemfile.$gemfile_version --path vendor
          done

    - save_cache:
        key: bundler-cache-{{.Environment.RUBY_VERSION}}-{{checksum "bundler_checksum"}}
        paths:
          # Cache Gemfile.locks, and vendored gems are also under this directory.
          - spec/gemfiles

    - run:
        command: |
          for version in $PG_VERSIONS
          do
            echo "host all all 127.0.0.1/32 trust" > /etc/postgresql/$version/main/pg_hba.conf
            echo "local all all trust" >> /etc/postgresql/$version/main/pg_hba.conf
          done

    # From: https://github.com/nimiq/docker-postgresql93/issues/2
    - run: mkdir /etc/ssl/private-copy; mv /etc/ssl/private/* /etc/ssl/private-copy/; rm -r /etc/ssl/private; mv /etc/ssl/private-copy /etc/ssl/private; chmod -R 0700 /etc/ssl/private; chown -R postgres /etc/ssl/private
    - run: service postgresql start
    - run: for port in $PG_PORTS; do createdb que-test -U postgres -p $port; done

    - run:
        command: |
          for port in $PG_PORTS
          do
            for gemfile_version in $GEMFILE_VERSIONS
            do
              DATABASE_URL="postgres://postgres:postgres@localhost:$port/que-test" BUNDLE_GEMFILE="spec/gemfiles/Gemfile.$gemfile_version" TEST_OPTS="--verbose --profile" rvm $RUBY_VERSION do bundle exec rake
            done
          done

version: 2
jobs:
  ruby_2_2:
    <<: *defaults
    environment:
      - RUBY_VERSION: 2.2

  ruby_2_3:
    <<: *defaults
    environment:
      - RUBY_VERSION: 2.3

  ruby_2_4:
    <<: *defaults
    environment:
      - RUBY_VERSION: 2.4

workflows:
  version: 2
  build_all_rubies:
    jobs:
      ruby_2_2
      ruby_2_3
      ruby_2_4
